from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable
)
import io
import os
import aiofiles


def generate_pdf(proposal_text: str, lead_name: str = "Client") -> bytes:
    """Generate a styled PDF proposal"""
    buffer = io.BytesIO()
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )
    
    # Styles
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=24,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=12
    )
    
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#16213e"),
        spaceBefore=16,
        spaceAfter=8
    )
    
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
        textColor=colors.HexColor("#333333")
    )
    
    # Build content
    content = []
    
    # Header
    content.append(Paragraph("AgentIQ", title_style))
    content.append(Paragraph(f"Sales Proposal for {lead_name}", heading_style))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
    content.append(Spacer(1, 20))
    
    # Parse and add proposal text
    for line in proposal_text.split("\n"):
        line = line.strip()
        if not line:
            content.append(Spacer(1, 8))
        elif line.startswith("##"):
            content.append(Paragraph(line.replace("##", "").strip(), heading_style))
        elif line.startswith("#"):
            content.append(Paragraph(line.replace("#", "").strip(), title_style))
        else:
            content.append(Paragraph(line, body_style))
    
    # Footer spacer
    content.append(Spacer(1, 30))
    content.append(HRFlowable(width="100%", thickness=0.5, color=colors.gray))
    content.append(Paragraph(
        "Generated by AgentIQ — AI-Powered Sales Automation",
        ParagraphStyle("footer", parent=styles["Normal"],
                      fontSize=9, textColor=colors.gray,
                      alignment=1)
    ))
    
    doc.build(content)
    buffer.seek(0)
    return buffer.read()


async def save_pdf(pdf_bytes: bytes, filename: str = "proposal.pdf") -> str:
    """Save PDF to tmp folder"""
    path = f"tmp/{filename}"
    async with aiofiles.open(path, "wb") as f:
        await f.write(pdf_bytes)
    return path